-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.users
(
    id integer NOT NULL,
    firstname text NOT NULL,
    surname text NOT NULL,
    password text NOT NULL,
    repeatpassword text NOT NULL,
    mail character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    companyname text NOT NULL,
    website text NOT NULL,
    user_id integer NOT NULL,
    "id " integer NOT NULL,
    phone character varying(11) NOT NULL,
    PRIMARY KEY ("id ")
) INHERITS (users);

CREATE TABLE public.jobseekers
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    birthdate date NOT NULL,
    nationalid character varying(11) NOT NULL,
    PRIMARY KEY (id)
) inherits(users);

CREATE TABLE public.jobpositions
(
    id integer NOT NULL,
    name character varying(80) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_personnel
(
    user_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.activation_email
(
    employer_id integer NOT NULL,
    PRIMARY KEY (employer_id)
);

CREATE TABLE public.activation_mernis
(
    jobseeker_id integer NOT NULL,
    PRIMARY KEY (jobseeker_id)
) inherits(jobseekers);

CREATE TABLE public.activation_systemp
(
    confirmation boolean NOT NULL,
    confirm_date date NOT NULL,
    user_id integer NOT NULL
);

ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.jobseekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.system_personnel
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.activation_email
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers ("id ")
    NOT VALID;


ALTER TABLE public.activation_mernis
    ADD FOREIGN KEY (jobseeker_id)
    REFERENCES public.jobseekers (id)
    NOT VALID;


ALTER TABLE public.activation_systemp
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;